default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todo_application_development
  password: postgres

test:
  <<: *default
  database: todo_application_test
  password: postgres